# Generated by Django 3.2.2 on 2021-07-15 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='call_state',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('RECEIVING', 'Receiving'), ('CALLING', 'Calling'), ('ONCALL', 'Oncall')], default='IDLE', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='other_caller',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile'),
        ),
    ]
